In [1]:
# https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1

# id
# title
# release_date
# overview
# popularity
# vote_average
# vote_count


# 10921 * 7

In [2]:
import pandas as pd
import requests

In [3]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [4]:
pd.DataFrame(response.json()['results'])[['id','title','release_date','overview','popularity','vote_average','vote_count']]

,id,title,release_date,overview,popularity,vote_average,vote_count
0,1007757,Swapped,2026-05-01,"A small woodland creature and a majestic bird,...",174.8725,8.967,1672
1,278,The Shawshank Redemption,1994-09-23,Imprisoned in the 1940s for the double murder ...,86.5493,8.722,30557
2,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",41.3768,8.688,23032
3,687163,Project Hail Mary,2026-03-15,Science teacher Ryland Grace wakes up on a spa...,165.5349,8.673,5027
4,936075,Michael,2026-04-22,"The story of Michael Jackson, one of the most ...",522.2704,8.583,2251
5,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,27.6492,8.572,13965
6,1330021,Remarkably Bright Creatures,2026-05-07,Through unlikely bonds formed during night shi...,35.3840,8.568,609
7,424,Schindler's List,1993-12-15,The true story of how businessman Oskar Schind...,23.5781,8.569,17511
8,389,12 Angry Men,1957-04-10,The defense and the prosecution have rested an...,22.2588,8.562,10036
9,129,Spirited Away,2001-07-20,"A young girl, Chihiro, becomes trapped in a st...",29.8100,8.535,18399
10,155,The Dark Knight,2008-07-16,Batman raises the stakes in his war on crime. ...,42.5479,8.531,35896
11,19404,Dilwale Dulhania Le Jayenge,1995-10-20,"Raj is a rich, carefree, happy-go-lucky second...",15.6531,8.513,4593
12,497,The Green Mile,1999-12-10,A supernatural tale set on death row in a Sout...,26.1348,8.507,19323
13,122,The Lord of the Rings: The Return of the King,2003-12-17,As armies mass for a final battle that will de...,43.1667,8.500,26640
14,496243,Parasite,2019-05-30,"All unemployed, Ki-taek's family takes peculia...",33.4113,8.494,20722
15,1181678,¿Quieres ser mi hijo?,2023-09-21,"Lu, a conformist woman in her forties, learns ...",9.9611,8.500,354
16,680,Pulp Fiction,1994-09-10,"A burger-loving hit man, his philosophical par...",32.7957,8.483,30273
17,372058,Your Name.,2016-08-26,High schoolers Mitsuha and Taki are complete s...,25.2212,8.481,12612
18,157336,Interstellar,2014-11-05,The adventures of a group of explorers who mak...,68.9288,8.478,40005
19,429,"The Good, the Bad and the Ugly",1966-12-23,While the Civil War rages on between the Union...,19.6494,8.468,9683

In [5]:
df = pd.DataFrame()

In [6]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1, 548):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','release_date','overview','popularity','vote_average','vote_count']]
    df = df.append(temp_df, ignore_index=True)

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [ ]:
df

In [ ]:
df.shape

In [ ]:
df.to_csv('movies.csv')