In [63]:
import numpy as np 
import pandas as pd

In [64]:
data = pd.read_csv('PlayTennis.csv')
data.head()

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

In [65]:
data

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

## Problem 1:

## Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
## Play or Not Play?

## Solution

#### P(Yes | Sunny, Hot, High, Weak) = P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes) * P(Yes)

#### P (No | Sunny, Hot, High, Weak) = P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No) * P(No)

#### Compare and Decide using the Maximum A Posteriori Rule (MAP)

## Problem 2:

## Outlook=Overcast, Temp=Cold, Humidity=Low, Wind=Weak
## Play or Not Play?

## Solution

#### P(Yes | Overcast, Cold, Low, Weak) = P(Overcast | Yes) * P(Cold | Yes) * P(Low | Yes) * P(Weak | Yes) * P(Yes)

#### P (No | Overcast, Cold, Low, Weak) = P(Overcast | No) * P(Cold | No) * P(Low | No) * P(Weak | No) * P(No)

#### Compare and Decide using the Maximum A Posteriori Rule (MAP)

In [66]:
# Training

# Lookup Table(Dictionary) # Loops in dataset and store all the probabilities in Lookup Table

# Testing

In [67]:
# P(Yes)
data['Play Tennis'].value_counts()

# P(No)

Play Tennis
Yes    9
No     5
Name: count, dtype: int64

In [68]:
py = 9/14
pn = 4/14

In [69]:
print(py)
print(pn)

0.6428571428571429
0.2857142857142857

In [70]:
# Outlook

pd.crosstab(data['Outlook'], data['Play Tennis'])

Play Tennis  No  Yes
Outlook
Overcast      0    4
Rain          2    3
Sunny         3    2

In [71]:
Pon = 0 # Probabitlity of Outlook for No
Prn = 2/5
Psn = 3/5

Poy = 4/9 # Probability of outlook for Yes
Pry = 3/9
Psy = 2/9

In [72]:
# Temperature

pd.crosstab(data['Temperature'], data['Play Tennis'])

Play Tennis  No  Yes
Temperature
Cool          1    3
Hot           2    2
Mild          2    4

In [73]:
PCoolNo = 1/5
PhotNo = 2/5
PHotNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [74]:
# Humidity

pd.crosstab(data['Humidity'], data['Play Tennis'])

Play Tennis  No  Yes
Humidity
High          4    3
Normal        1    6

In [75]:
PHighNo = 4/5
PNormalNo = 1/5

PHighYes = 3/9
PNormalYes = 6/9

In [76]:
# Wind

pd.crosstab(data['Wind'], data['Play Tennis'])

Play Tennis  No  Yes
Wind
Strong        3    3
Weak          2    6

In [77]:
PStrongNo = 3/5
PWeakNo = 2/5

PStrongYes = 3/9
PWeakYes = 6/9

In [78]:
## Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak

Pyes = py * Psy * PHotYes * PHighYes * PWeakYes
print(Pyes)

0.007054673721340388

In [79]:

PNo = pn * Psn * PHotNo * PHighNo * PWeakNo
print(PNo)

0.021942857142857142

In [80]:
# As The Proabability of PNo > PYes. Therefore, the we do not play